title: CSCI 160
author: CSBSJU
description: Course materials for CSCI 160.
lang: en
timezone: UTC
exclude:
  - AUTHORS
  - Gemfile
  - LICENSE
  - LICENSE.MIT

plugins:
  - jekyll-remote-theme
  
remote_theme: yous/whiteglass
