// MouseEvent
import java.awt.event.MouseEvent;

// GraphicsProgram
import acm.program.GraphicsProgram;

// GCanvas, GLabel
import acm.graphics.*;

// RandomGenerator
import acm.util.*;


/**
 * A race program between a hare and a turtle
 */
public class NewRace extends GraphicsProgram
{
  // x-coordinate for start line
  private static final int X_STARTLINE   =  28;
  // x-coordinate for hare
  private static final int HARE_X        =   5;
  // y-coordinate for hare
  private static final int HARE_Y        =  20;
  // size of hare
  private static final int HARE_SIZE     =  40;
  // x-coordinate for turtle
  private static final int TURTLE_X      =   5;
  // y-coordinate for turtle
  private static final int TURTLE_Y      = 100;
  // size of turtle
  private static final int TURTLE_SIZE   =  40;
  // x-coordinate for instruction label
  private static final int INSTRUCTION_X = 100;
  // y-coordinate for instruction label
  private static final int INSTRUCTION_Y =  40;
 
  // x-coordinate of end line 
  private int xEndLine;
  // canvas
  private GCanvas canvas;
  // label for instructions
  private GLabel instructions;


  /**
   * Initialize the canvas
   */
  public void init()
  {
    // store a reference to the canvas
    this.canvas = this.getGCanvas();

    // calculate the x-coordinate for the end line
    this.xEndLine = this.canvas.getWidth() - 70;
   
    int height = this.canvas.getHeight();
    this.canvas.add(new GLine(X_STARTLINE, 0, X_STARTLINE, height));
    this.canvas.add(new GLine(xEndLine, 0, xEndLine, height));

    // display instructions
    this.instructions = new GLabel("Click to begin the race");
    this.add(this.instructions, INSTRUCTION_X, INSTRUCTION_Y);

    // enable mouse click functionality
    this.addMouseListeners();
  }
 

  /**
   * Create and start the racers 
   *
   * @param e the event generated by the mouse click
   */
  public void mouseClicked(MouseEvent e)
  {
    // hide the instructions once they've been followed
    this.instructions.setVisible(false);

    // calculate racer speeds
    RandomGenerator rand = new RandomGenerator();
    int hareSpeed   = 2 + rand.nextInt(8); // average of 5.5 for the hare but a wide range.
    int turtleSpeed = 4 + rand.nextInt(3); // average of 5 for the turtle but a narrow range.
 
    // create turtle and hare and start them
    ActiveHare hare     = new ActiveHare(HARE_X, HARE_Y, HARE_SIZE, xEndLine, hareSpeed, canvas);
    ActiveTurtle turtle = new ActiveTurtle(TURTLE_X, TURTLE_Y, TURTLE_SIZE, xEndLine, turtleSpeed, canvas);

    // start the racers
    hare.start();
    turtle.start();
  }
}
